### ISSUE TITLE
Heartbeat May Send on Closed Socket

### ISSUE THREAD

**Issue by IGJoshua** [IGJoshua/discljord#47]
**Describe the bug**
There seems to be a race condition where an already-closed websocket will have a heartbeat take place before the close event hits, causing an exception to be thrown and the bot to crash.

**Version Information**
 - Clojure Version: 1.10.1
 - Discljord Version: 1.0.0-RC1
 - OS bot is hosted on: Raspbian

**To Reproduce**
1. Start a bot
2. Wait until a disconnect occurs during a heartbeat
3. Pray you hit it (or don't, depending)
4. If you hit it, an exception gets thrown and the entire event loop for shards gets thrown off because that shard returns as nil

Minimal reproduction case:
Happens on the current version of alexis-texas, however probably happens on all bots.

**Expected behavior**
If the heartbeat is sent on a closed channel, the websocket should probably be dissoc'ed from the shard, but the shard should return as normal.

**Logs**
```
20-07-10 17:06:52 raspberrypi DEBUG [discljord.connections.impl:205] - Websocket closed with code: 1006 and message: Disconnected
20-07-10 17:06:52 raspberrypi DEBUG [discljord.connections.impl:550] - Will try to connect in 0 seconds
20-07-10 17:06:52 raspberrypi DEBUG [discljord.connections.impl:552] - Sending reconnect signal to shard 0
20-07-10 17:06:52 raspberrypi DEBUG [discljord.connections.impl:342] - Received connection event on shard 0
20-07-10 17:06:52 raspberrypi INFO [discljord.connections.impl:316] - Connecting shard 0
20-07-10 17:06:52 raspberrypi DEBUG [discljord.connections.impl:190] - Starting websocket of size 2147483647 at url wss://gateway.discord.gg
20-07-10 17:06:53 raspberrypi DEBUG [discljord.connections.impl:532] - Sending resume payload for shard 0 with session 24b22118bc520e0b912bcc0e749c8b81 and seq 6987
20-07-10 17:06:53 raspberrypi DEBUG [discljord.connections.impl:440] - Starting a heartbeat with interval 41250 on shard 0
20-07-10 17:06:53 raspberrypi DEBUG [discljord.connections.impl:205] - Websocket closed with code: 1006 and message: Disconnected
Exception in thread "async-dispatch-1" java.lang.Error: java.util.concurrent.ExecutionException: java.nio.channels.ClosedChannelException
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1155)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at clojure.core.async.impl.concurrent$counted_thread_factory$reify__4960$fn__4961.invoke(concurrent.clj:29)
        at clojure.lang.AFn.run(AFn.java:22)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.util.concurrent.ExecutionException: java.nio.channels.ClosedChannelException
        at org.eclipse.jetty.util.FutureCallback.get(FutureCallback.java:123)
        at org.eclipse.jetty.util.FutureCallback.get(FutureCallback.java:30)
        at clojure.core$deref_future.invokeStatic(core.clj:2300)
        at clojure.core$deref.invokeStatic(core.clj:2320)
        at clojure.core$deref.invoke(core.clj:2306)
        at gniazdo.core$eval21332$fn__21333.invoke(core.clj:21)
        at gniazdo.core$eval21313$fn__21314$G__21304__21321.invoke(core.clj:17)
        at gniazdo.core$connect_with_client$reify__21416.send_msg(core.clj:138)
        at discljord.connections.impl$step_shard_BANG_$heartbeat_fn__21675.invoke(impl.clj:351)
        at discljord.connections.impl$step_shard_BANG_$fn__21825$state_machine__10254__auto____21852$fn__21854.invoke(impl.clj:390)
        at discljord.connections.impl$step_shard_BANG_$fn__21825$state_machine__10254__auto____21852.invoke(impl.clj:378)
        at clojure.core.async.impl.ioc_macros$run_state_machine.invokeStatic(ioc_macros.clj:978)
        at clojure.core.async.impl.ioc_macros$run_state_machine.invoke(ioc_macros.clj:977)
        at clojure.core.async.impl.ioc_macros$run_state_machine_wrapped.invokeStatic(ioc_macros.clj:982)
        at clojure.core.async.impl.ioc_macros$run_state_machine_wrapped.invoke(ioc_macros.clj:980)
        at discljord.connections.impl$step_shard_BANG_$fn__21825.invoke(impl.clj:378)
        at clojure.lang.AFn.run(AFn.java:22)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        ... 4 more
Caused by: java.nio.channels.ClosedChannelException
        at org.eclipse.jetty.websocket.common.io.FrameFlusher.enqueue(FrameFlusher.java:109)
        at org.eclipse.jetty.websocket.common.io.AbstractWebSocketConnection.outgoingFrame(AbstractWebSocketConnection.java:582)
        at org.eclipse.jetty.websocket.client.io.WebSocketClientConnection.outgoingFrame(WebSocketClientConnection.java:58)
        at org.eclipse.jetty.websocket.common.extensions.ExtensionStack$Flusher.process(ExtensionStack.java:400)
        at org.eclipse.jetty.util.IteratingCallback.processing(IteratingCallback.java:241)
        at org.eclipse.jetty.util.IteratingCallback.iterate(IteratingCallback.java:223)
        at org.eclipse.jetty.websocket.common.extensions.ExtensionStack.outgoingFrame(ExtensionStack.java:277)
        at org.eclipse.jetty.websocket.common.WebSocketSession.outgoingFrame(WebSocketSession.java:359)
        at org.eclipse.jetty.websocket.common.WebSocketRemoteEndpoint.uncheckedSendFrame(WebSocketRemoteEndpoint.java:306)
        at org.eclipse.jetty.websocket.common.WebSocketRemoteEndpoint.sendAsyncFrame(WebSocketRemoteEndpoint.java:240)
        at org.eclipse.jetty.websocket.common.WebSocketRemoteEndpoint.sendStringByFuture(WebSocketRemoteEndpoint.java:403)
        at gniazdo.core$eval21332$fn__21333.invoke(core.clj:24)
        ... 16 more
20-07-10 17:06:53 raspberrypi DEBUG [alexis-texas.events:175] - Disconnecting from Discord.
```

**Additional Context**
This particular error has likely been in bots since the most recent websocket rewrite, but has only surfaced now, which means it's an incredibly rare race condition (which should be no surprise given it's highly scheduler-dependent and requires disconnects which are intermittent and rare to line up perfectly with an event which happens consistently approximately every 40 seconds). The particular bot it had been running on was running for 18 days straight before it became an issue.

**Comment by IGJoshua** [comment]
This got fixed as a part of the release branch of 1.1.0
