### ISSUE TITLE
Does anything work?

### ISSUE THREAD

**Issue by lensgolda** [IGJoshua/discljord#74]
After some struggle, i have been take exact examples from readme, passed my bot token and channel id (bot already authorized with all priveleges on my server), and got no one event, only unusefull very looooong DEBUG traces.

- clojure 1.10.3
- JDK 11
- discljord 1.2.2

```bash
clj -M -m my.main-fn.namespace.core 
```

Code

```clojure
(defonce system (atom nil))

(defn -main [& args]
  (let [config (edn/read-string (slurp "config.edn"))

        {token :bot-token
         channel :channel-id} (:discord config)

        event-ch      (a/chan 100)
        connection-ch (c/connect-bot! token event-ch :intents [:message-create])
        message-ch    (m/start-connection! token)]
    (try
      (loop []
        (let [[event-type event-data] (a/<!! event-ch)]
          (log/info ">>> discord >>>" event-type event-data)
          (when (and
                  (= :message-create event-type)
                  (= (:channel-id event-data) channel)
                  (not (:bot (:author event-data))))
            (let [message-content (:content event-data)]
              (if (= "!exit" (s/trim (s/lower-case message-content)))
                (do
                  (m/create-message! message-ch channel :content "Goodbye!")
                  (c/disconnect-bot! connection-ch))
                (m/create-message! message-ch channel :content message-content))))
          (when (= :channel-pins-update event-type)
            (c/disconnect-bot! connection-ch))
          (when-not (= :disconnect event-type)
            (recur))))
      (finally
        (m/stop-connection! message-ch)
        (a/close!           event-ch)
        (.addShutdownHook (Runtime/getRuntime)
          (Thread. #(component/stop system)))))
    (.addShutdownHook (Runtime/getRuntime)
      (Thread. #(component/stop system)))))
```

Got result: Nothing happened when i send messages on channel, send private messages to Bot, i tried to specify different intents, and without intents specified. But nothing happened at all, got no one event catched.

Found only one NPE anomaly in traces. All the rest traces seemed like about websockets connections to discord DEBUG info and looks OK. Thousand or more lines, so i will not paste that here.

```bash
09:21:02.289 [HttpClient@2a230da9-21] DEBUG o.eclipse.jetty.client.HttpReceiver - 
java.lang.NullPointerException: null
	at org.eclipse.jetty.client.http.HttpReceiverOverHTTP.parse(HttpReceiverOverHTTP.java:218) ~[jetty-client-9.4.35.v20201120.jar:9.4.35.v20201120]
	at org.eclipse.jetty.client.http.HttpReceiverOverHTTP.process(HttpReceiverOverHTTP.java:144) ~[jetty-client-9.4.35.v20201120.jar:9.4.35.v20201120]
	at org.eclipse.jetty.client.http.HttpReceiverOverHTTP.receive(HttpReceiverOverHTTP.java:79) ~[jetty-client-9.4.35.v20201120.jar:9.4.35.v20201120]
	at org.eclipse.jetty.client.http.HttpChannelOverHTTP.receive(HttpChannelOverHTTP.java:131) ~[jetty-client-9.4.35.v20201120.jar:9.4.35.v20201120]
	at org.eclipse.jetty.client.http.HttpConnectionOverHTTP.onFillable(HttpConnectionOverHTTP.java:169) ~[jetty-client-9.4.35.v20201120.jar:9.4.35.v20201120]
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311) ~[jetty-io-9.4.35.v20201120.jar:9.4.35.v20201120]
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:105) ~[jetty-io-9.4.35.v20201120.jar:9.4.35.v20201120]
	at org.eclipse.jetty.io.ssl.SslConnection$DecryptedEndPoint.onFillable(SslConnection.java:540) ~[jetty-io-9.4.35.v20201120.jar:9.4.35.v20201120]
	at org.eclipse.jetty.io.ssl.SslConnection.onFillable(SslConnection.java:395) ~[jetty-io-9.4.35.v20201120.jar:9.4.35.v20201120]
	at org.eclipse.jetty.io.ssl.SslConnection$2.succeeded(SslConnection.java:161) ~[jetty-io-9.4.35.v20201120.jar:9.4.35.v20201120]
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:105) ~[jetty-io-9.4.35.v20201120.jar:9.4.35.v20201120]
	at org.eclipse.jetty.io.ChannelEndPoint$1.run(ChannelEndPoint.java:104) ~[jetty-io-9.4.35.v20201120.jar:9.4.35.v20201120]
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:336) ~[jetty-util-9.4.35.v20201120.jar:9.4.35.v20201120]
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:313) ~[jetty-util-9.4.35.v20201120.jar:9.4.35.v20201120]
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:171) ~[jetty-util-9.4.35.v20201120.jar:9.4.35.v20201120]
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.produce(EatWhatYouKill.java:135) ~[jetty-util-9.4.35.v20201120.jar:9.4.35.v20201120]
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:773) ~[jetty-util-9.4.35.v20201120.jar:9.4.35.v20201120]
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:905) ~[jetty-util-9.4.35.v20201120.jar:9.4.35.v20201120]
	at java.base/java.lang.Thread.run(Thread.java:834) ~[na:na]
```

And typical trace ends and looks like

```
09:34:47.562 [HttpClient@2a230da9-26] DEBUG o.eclipse.jetty.io.ssl.SslConnection - <c.onFillable SslConnection@438afa8b::SocketChannelEndPoint@3f61280{l=/192.168.31.104:62398,r=gateway.discord.gg/162.159.135.234:443,OPEN,fill=FI,flush=-,to=3/300000}{io=0/1,kio=0,kro=1}->SslConnection@438afa8b{NOT_HANDSHAKING,eio=-1/-1,di=-1,fill=INTERESTED,flush=IDLE}~>DecryptedEndPoint@bcf67a6{l=/192.168.31.104:62398,r=gateway.discord.gg/162.159.135.234:443,OPEN,fill=FI,flush=-,to=6/300000}=>WebSocketClientConnection@4288bdd5[s=ConnectionState@60831858[OPENED],f=org.eclipse.jetty.websocket.common.io.AbstractWebSocketConnection$Flusher@57ffda8c[IDLE][queueSize=0,aggregateSize=-1,terminated=null],g=Generator[CLIENT,validating],p=Parser@6013dfed[ExtensionStack,s=START,c=0,len=8,f=null]]
09:34:47.562 [HttpClient@2a230da9-32] DEBUG org.eclipse.jetty.io.ManagedSelector - Selector sun.nio.ch.KQueueSelectorImpl@687f563a woken up from select, 0/0/1 selected
09:34:47.562 [HttpClient@2a230da9-26] DEBUG o.e.j.u.t.ReservedThreadExecutor - ReservedThreadExecutor@86735aa{s=2/12,p=0}@47aa5031 waiting
09:34:47.563 [HttpClient@2a230da9-32] DEBUG org.eclipse.jetty.io.ManagedSelector - Selector sun.nio.ch.KQueueSelectorImpl@687f563a processing 0 keys, 1 updates
09:34:47.563 [HttpClient@2a230da9-32] DEBUG org.eclipse.jetty.io.ManagedSelector - updateable 1
09:34:47.563 [HttpClient@2a230da9-32] DEBUG org.eclipse.jetty.io.ManagedSelector - update org.eclipse.jetty.io.ChannelEndPoint$$Lambda$132/0x0000000801f3bc40@5aa2bb5
09:34:47.563 [HttpClient@2a230da9-32] DEBUG org.eclipse.jetty.io.ChannelEndPoint - Key interests updated 0 -> 1 on SocketChannelEndPoint@3f61280{l=/192.168.31.104:62398,r=gateway.discord.gg/162.159.135.234:443,OPEN,fill=FI,flush=-,to=4/300000}{io=1/1,kio=1,kro=1}->SslConnection@438afa8b{NOT_HANDSHAKING,eio=-1/-1,di=-1,fill=INTERESTED,flush=IDLE}~>DecryptedEndPoint@bcf67a6{l=/192.168.31.104:62398,r=gateway.discord.gg/162.159.135.234:443,OPEN,fill=FI,flush=-,to=7/300000}=>WebSocketClientConnection@4288bdd5[s=ConnectionState@60831858[OPENED],f=org.eclipse.jetty.websocket.common.io.AbstractWebSocketConnection$Flusher@57ffda8c[IDLE][queueSize=0,aggregateSize=-1,terminated=null],g=Generator[CLIENT,validating],p=Parser@6013dfed[ExtensionStack,s=START,c=0,len=8,f=null]]
09:34:47.565 [HttpClient@2a230da9-32] DEBUG org.eclipse.jetty.io.ManagedSelector - updates 0
09:34:47.565 [HttpClient@2a230da9-32] DEBUG org.eclipse.jetty.io.ManagedSelector - Selector sun.nio.ch.KQueueSelectorImpl@687f563a waiting with 1 keys

```

**Comment by JohnnyJayJay** [comment]
`:message-create` is not an intent. The one you need to receive (guild) message create events is `:guild-messages`. Although you should still receive guild create events and ready events in the current state.
The readme needs to be updated in that regard, the examples don't use intents yet.

For logging, [you need to add a logger implementation](https://github.com/IGJoshua/discljord#logging) such as log4j2 or logback. That will allow you to customise the logging output.

**Comment by lensgolda** [comment]
> `:message-create` is not an intent. The one you need to receive (guild) message create events is `:guild-messages`. Although you should still receive guild create events and ready events in the current state.
> The readme needs to be updated in that regard, the examples don't use intents yet.

as i said, i tried all intents, and without them at all, and `:guild-messages` too, result is the same

> For logging, [you need to add a logger implementation](https://github.com/IGJoshua/discljord#logging) such as log4j2 or logback. That will allow you to customise the logging output.

For logging i'm using logback with clojure.tools.logging, and everything is ok with logs.

**Comment by lensgolda** [comment]
i changed logging to `slf4j-simple`, and connection string to `(c/connect-bot! token event-ch :intents #{:guild-messages})` and it works now like a charm. Thank's, you can close the issue.

**Comment by IGJoshua** [comment]
I'm sorry you've been having troubles getting it set up! One thing that may prove useful to you is to turn on spec instrumentation as evety public fn in discljord has a spec, and it would catch errors like the incorrect intents.
